project:
  type: website
  output-dir: docs

website:
  title: "Supplements"
  navbar:
    pinned: true
    title: false
    left:
      - text: "Code and Supplements"
        menu: 
          - text: "Supplements"
            href: index.qmd
          - text: "Answers to selected exercises"
            href: https://jhmaindonald.github.io/PGRselected/
          - text: "Afterword"
            href: afterword.qmd
            
      - text: "Practical Guide"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "R code"
        href: https://ten-z.github.io/PGRTestBook/
        
    right: 
      - text: "Resources"
        menu:
          - text: "Ways to Use Code"
            href: RunningCode.qmd
          - text: "Code for Selected Figures"
            href: figFuns.qmd
            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

