project:
  type: website
  output-dir: docs

website:
  title: "Supplements"
  repo-branch: main
  navbar:
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Practical Guide"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "R code"
        href: https://ten-z.github.io/PGRTestBook/
        
    right: 
      - text: "Resources"
        menu:
          - text: "Afterword"
            href: afterword.qmd
          - text: "Ways to Use Code"
            href: RunningCode.qmd
          - text: "Code for Selected Figures"
            href: figFuns.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

