project:
  type: website
  output-dir: docs

website:
  title: "A Practical Guide . . . -- Code and Supplements"
  navbar:
    pinned: true
    title: false
    left:
      - text: "Main"
        menu: 
          - text: "Overview"
            href: index.qmd
          - text: "Chapter contents -- Summary"
            href: about.qmd
          - text: "Afterword"
            href: afterword.qmd
          - text: "Corrections"
            href: corrections.qmd
      - text: "R Code"   
        menu:
          - text: "R code"
            href: https://jhmaindonald.github.io/Rcode/
          - text: "Ways to Use Code"
            href: RunningCode.qmd
          - text: "Code for Selected Figures"
            href: figFuns.qmd    
            
      - text: "Blog"
        href: blog.qmd
        
    right: 
      - text: "Additional Notes"
        menu:
          - text: "Answers to selected exercises"
            href: https://jhmaindonald.github.io/PGRselected/
          - text: "Bayes Factors & the BIC Statistic"
            href: bf.qmd
            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

