project:
  type: website
  output-dir: docs

website:
  title: "Supplements"
  repo-branch: main
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - href: afterword.qmd
        text: Afterword
      - href: RunningCode.qmd
        text: 'Ways to Use Code'
      - href: figFuns.qmd
        text: 'Code for Selected Figures'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

