---
title: "Create static html files for posting to GitHub"
author: "John Maindonald"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create static html files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r echo=F}
options(rmarkdown.html_vignette.check_title = FALSE)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This "vignette" records steps that can be followed when a vignette 
is changed or added, prior to committing changes that include static
html files to GitHub.

```{r exampleCode, eval=F}
tools::buildVignettes(dir = ".", tangle=TRUE)
if(!dir.exists('inst'))dir.create("~/pkgs/PGRcode/inst")   
if(!dir.exists('inst/doc'))dir.create("~/pkgs/PGRcode/inst/doc") 
## On installation, files in 'inst/doc/' are copied to 'doc/'
file.copy(dir("vignettes", full.names=TRUE), "~/pkgs/PGRcode/inst/doc", overwrite=TRUE)
```
Details of using pkgdown to set up the web page can be found at
https://pkgdown.r-lib.org/articles/pkgdown.html#configuration

```{r setupCode, eval=F}
usethis::use_pkgdown()
pkgdown::build_site()
usethis::use_pkgdown_github_pages()
usethis::use_github_action("render-rmarkdown")
usethis::use_github_action("check-release")
```


